### ISSUE TITLE
complete serde serialization/de-serialization for Programs

### ISSUE THREAD

**Issue by kellpossible** [kellpossible/doublecount#2]

**Comment by mk270** [comment]
This would be lovely; I am currently serialising to and from sqlite to work around it

**Comment by kellpossible** [comment]
Cool! I didn't yet have a use case for this myself, so I had left this undone. I'll try to get it done this week. Hopefully it isn't too painful, I did already refactor out some `Rc` pointers into id references instead to try to make this easier to do.

**Comment by kellpossible** [comment]
hey @mk270 I've completed the serde support for `Program` do you think this will be enough for your use case?

**Comment by mk270** [comment]
It seems to be, yes! Thank you very much!

**Comment by kellpossible** [comment]
Great! I'll close this one for now then
