### ISSUE TITLE
allow AccountID to be set manually

### ISSUE THREAD

**Issue by mk270** [kellpossible/doublecount#8]
When re-loading data that has been serialised out of doublecount (e.g., to sqlite or serde once that's working), it'd be nice to be able to get the same ID for Account objects. Would this be Ok, or is there some good reason not to do it?

**Comment by kellpossible** [comment]
I think I may have inadvertently fixed this and perhaps forgotten to make note of it in the change log in commit https://github.com/kellpossible/doublecount/commit/7d87391e5083935d5642795b0f9e43ca8de76c6a the [Account::new()](https://docs.rs/doublecount/0.8.0/doublecount/struct.Account.html#method.new) method was altered to allow this. Let me know if it seems like this would fit your use case.

**Comment by mk270** [comment]
yes, I saw that. Was going to send a PR to update the example material in the docs
